# Generated by Django 5.0.6 on 2024-05-16 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0004_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='patient_image',
            field=models.ImageField(default=1, upload_to='media/comments/'),
            preserve_default=False,
        ),
    ]
