# Generated by Django 5.0.6 on 2024-05-19 11:13

import clinic.helpers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0006_contact_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='patient_image',
            field=models.ImageField(upload_to=clinic.helpers.SaveMediaFiles.comments_image_path),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='image',
            field=models.ImageField(upload_to=clinic.helpers.SaveMediaFiles.doctor_image_path),
        ),
    ]
